import { Course, Profile, CBTExam, CBTAttempt, LiveRoom, LiveParticipant, LiveChatMessage, SubscriptionPlan, IntranetAccessRequest, IntranetBulletin, TutoringAttendanceSession } from '@/types';

export const DEFAULT_INSTRUCTOR_PROFILE: Profile = {
  id: 'faculty_author_001',
  email: 'faculty@reactjav.io',
  full_name: 'Dr. Elena Chen',
  avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
  role: 'instructor',
  bio: 'Principal Architect & University Lecturer with 12+ years of distributed systems and web development experience.',
  created_at: '2025-11-01T08:00:00Z',
  subscription_status: 'active',
  subscription_plan: 'lifetime',
  admin_granted: true,
};

// Demo user accounts removed. Platform requires authentic registration and login.
export const DEMO_PROFILES: Record<string, Profile> = {};

export const INITIAL_COURSES: Course[] = [
  {
    id: 'crs_nextjs_supabase_01',
    instructor_id: 'usr_instructor_001',
    title: 'Full-Stack Modern Web Engineering with Next.js 15 & Supabase',
    slug: 'nextjs-supabase-web-engineering',
    description: 'Master production-ready web application development with React 19, Next.js App Router, Supabase PostgreSQL, Row-Level Security, and real-time state management.',
    category: 'Software Engineering',
    track: 'Software Engineering',
    level: 'Intermediate',
    outcome_hook: 'Build production-ready web applications with React 19, Next.js App Router, Supabase PostgreSQL, and Row-Level Security.',
    duration_weeks: 24,
    weekly_hours: '20-30 hrs/week',
    skills: ['Next.js 15', 'React 19', 'TypeScript', 'Supabase', 'PostgreSQL', 'Tailwind CSS'],
    sponsorship_note: 'Sponsored / $5/mo',
    is_now_open: true,
    is_popular: true,
    cohort_date: 'April 2026',
    price: 49.99,
    thumbnail_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    created_at: '2026-02-01T12:00:00Z',
    enrollments_count: 1420,
    average_rating: 4.9,
    reviews_count: 312,
    instructor: DEFAULT_INSTRUCTOR_PROFILE,
    sections: [
      {
        id: 'sec_01',
        course_id: 'crs_nextjs_supabase_01',
        title: 'Module 1: Architecture, Supabase Foundations & Authentication',
        position: 1,
        lessons: [
          {
            id: 'les_01_01',
            section_id: 'sec_01',
            title: '1.1 System Architecture & Database Design for High-Throughput LMS',
            type: 'video',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            content: 'In this session, we analyze the multi-tenant architecture, comparing client-side state models vs Next.js Server Components with Supabase RLS.',
            duration_seconds: 480,
            position: 1,
            is_free_preview: true,
            is_completed: true,
          },
          {
            id: 'les_01_02',
            section_id: 'sec_01',
            title: '1.2 Configuring Supabase PostgreSQL & Row Level Security (RLS) Policies',
            type: 'article',
            content: `### Row Level Security (RLS) in PostgreSQL

Row Level Security is the bedrock of multi-tenant security in Supabase. Unlike traditional backends where application code is entirely responsible for filtering rows (where a single missing WHERE clause leads to data leaks), Postgres RLS enforces security at the engine level.

#### Key Concepts:
1. **\`auth.uid()\`**: Returns the authenticated user's UUID from the JWT token.
2. **Policy Expressions**: Boolean expressions evaluated for every \`SELECT\`, \`INSERT\`, \`UPDATE\`, and \`DELETE\` query.

\`\`\`sql
-- Enable RLS
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;

-- Allow students to read only their own enrollments
CREATE POLICY "Student read own enrollments"
  ON public.enrollments
  FOR SELECT
  USING (auth.uid() = user_id);
\`\`\`

#### Best Practices for LMS Applications:
- Always index columns referenced in RLS policies (e.g. \`user_id\`, \`course_id\`).
- Use security definer functions judiciously for complex aggregation queries.
- Keep policies declarative and lean for maximum query planning efficiency.`,
            duration_seconds: 360,
            position: 2,
            is_free_preview: true,
            is_completed: false,
          },
          {
            id: 'les_01_03',
            section_id: 'sec_01',
            title: '1.3 Assessment: Architecture & Security Checkpoint',
            type: 'quiz',
            duration_seconds: 300,
            position: 3,
            is_free_preview: true,
            is_completed: false,
            quiz_questions: [
              {
                id: 'q_01',
                lesson_id: 'les_01_03',
                question: 'What is the primary advantage of Row Level Security (RLS) over application-level filtering?',
                options: [
                  'It compiles SQL into WebAssembly for faster execution',
                  'Postgres evaluates access policies directly in the database engine, preventing accidental data leaks',
                  'It eliminates the need for user authentication completely',
                  'It replaces primary keys with cryptographic hashes',
                ],
                correct_option_index: 1,
                explanation: 'RLS enforces access rules in the PostgreSQL core engine, ensuring no API endpoint or bug can bypass isolation.',
                position: 1,
              },
              {
                id: 'q_02',
                lesson_id: 'les_01_03',
                question: 'How does Supabase expose the currently logged-in user inside an RLS policy?',
                options: [
                  'Via the auth.uid() function extracted from the JWT payload',
                  'Via an HTTP header forwarded to the client',
                  'Via a global JavaScript session variable',
                  'Via localStorage in the browser',
                ],
                correct_option_index: 0,
                explanation: 'Supabase validates the incoming JWT and sets the Postgres session context, exposing auth.uid() to SQL policies.',
                position: 2,
              },
            ],
          },
        ],
      },
      {
        id: 'sec_02',
        course_id: 'crs_nextjs_supabase_01',
        title: 'Module 2: Video Streaming, HLS & Resumable Player Engine',
        position: 2,
        lessons: [
          {
            id: 'les_02_01',
            section_id: 'sec_02',
            title: '2.1 Adaptive Bitrate Streaming & Resumable Playback Checkpoints',
            type: 'video',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
            content: 'Deep dive into video chunking, buffer management, and persisting playback seconds to PostgreSQL on throttle windows.',
            duration_seconds: 620,
            position: 1,
            is_free_preview: false,
            is_completed: false,
          },
          {
            id: 'les_02_02',
            section_id: 'sec_02',
            title: '2.2 Real-time Progress Tracking with Optimistic UI Updates',
            type: 'article',
            content: `### Optimistic UI Patterns in Learning Systems

When a student clicks "Mark as Complete" or finishes a video module, the learning interface must reflect the completed state **instantaneously (<16ms)** without waiting for network roundtrips.

#### Implementation Pattern:
1. **Immediate Local Cache Update**: The React state updates the completion checkmark and recalculates progress bar percentage.
2. **Background Sync**: An asynchronous call pushes the \`lesson_progress\` update to Supabase.
3. **Rollback Handling**: If the network request fails due to connectivity loss, the state reverts and triggers an unobtrusive toast notification.

This pattern eliminates perceptual latency and produces a buttery-smooth desktop and mobile learning experience.`,
            duration_seconds: 400,
            position: 2,
            is_free_preview: false,
            is_completed: false,
          },
        ],
      },
    ],
  },
  {
    id: 'crs_data_analytics_01',
    instructor_id: 'usr_instructor_001',
    title: 'Data Analytics Career Accelerator: SQL, Power BI & Business Intelligence',
    slug: 'data-analytics-career-accelerator',
    description: 'Qualify for high-demand data analyst roles across global and African tech firms. Learn to transform raw data into high-leverage commercial decisions using advanced SQL, Power BI dashboards, and automated ETL pipelines.',
    category: 'AI & Data',
    track: 'AI & Data',
    level: 'Beginner',
    outcome_hook: 'Qualify for high-paying data analyst roles at companies across every industry.',
    duration_weeks: 24,
    weekly_hours: '20-30 hrs/week',
    skills: ['SQL', 'Power BI', 'Tableau', 'Excel Mastery', 'Python for Analysis', 'Data Modeling'],
    sponsorship_note: 'Sponsored / $5/mo',
    is_now_open: true,
    is_popular: true,
    cohort_date: 'April 2026',
    price: 49.99,
    thumbnail_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    created_at: '2026-02-05T10:00:00Z',
    enrollments_count: 3200,
    average_rating: 4.92,
    reviews_count: 512,
    instructor: DEFAULT_INSTRUCTOR_PROFILE,
    sections: [
      {
        id: 'sec_da_01',
        course_id: 'crs_data_analytics_01',
        title: 'Module 1: Relational Database Querying & Advanced SQL',
        position: 1,
        lessons: [
          {
            id: 'les_da_01',
            section_id: 'sec_da_01',
            title: '1.1 Window Functions, Common Table Expressions & Aggregations',
            type: 'video',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
            content: 'Master partitioning, ranking functions, and complex joins to query enterprise data warehouses with sub-second performance.',
            duration_seconds: 520,
            position: 1,
            is_free_preview: true,
            is_completed: false,
          },
          {
            id: 'les_da_02',
            section_id: 'sec_da_01',
            title: '1.2 SQL Business Case: Retention & Churn Analytics',
            type: 'article',
            content: `### Analyzing Customer Churn with SQL Window Functions

Cohort retention analysis is one of the most requested deliverables for professional data analysts.

\`\`\`sql
WITH monthly_activity AS (
  SELECT 
    user_id,
    DATE_TRUNC('month', activity_date) AS activity_month,
    FIRST_VALUE(DATE_TRUNC('month', activity_date)) OVER (
      PARTITION BY user_id ORDER BY activity_date
    ) AS cohort_month
  FROM user_events
)
SELECT 
  cohort_month,
  activity_month,
  COUNT(DISTINCT user_id) AS active_users
FROM monthly_activity
GROUP BY 1, 2
ORDER BY 1, 2;
\`\`\`

This pattern allows executive stakeholders to track subscriber lifetime value and optimize retention funnels.`,
            duration_seconds: 380,
            position: 2,
            is_free_preview: true,
            is_completed: false,
          },
        ],
      },
    ],
  },
  {
    id: 'crs_aice_03',
    instructor_id: 'usr_instructor_001',
    title: 'AI Career Essentials (AiCE): Workplace AI & Automation',
    slug: 'ai-career-essentials',
    description: 'The premier fast-track programme to supercharge your career with artificial intelligence. Learn prompt engineering, autonomous agents, workflow automation, and how to command 3x output across any profession.',
    category: 'AI & Data',
    track: 'AI & Data',
    level: 'Beginner',
    outcome_hook: 'Stay ahead of workplace shifts, command generative AI, and land roles that pay more.',
    duration_weeks: 6,
    weekly_hours: '15-20 hrs/week',
    skills: ['Prompt Engineering', 'ChatGPT & Claude', 'AI Automation', 'Midjourney', 'Zapier', 'Notion AI'],
    sponsorship_note: 'Fully Funded / Free Access',
    is_now_open: true,
    is_popular: true,
    cohort_date: 'Rolling Admissions',
    price: 0.00,
    thumbnail_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    created_at: '2026-02-12T08:00:00Z',
    enrollments_count: 8400,
    average_rating: 4.96,
    reviews_count: 1240,
    instructor: DEFAULT_INSTRUCTOR_PROFILE,
    sections: [
      {
        id: 'sec_aice_01',
        course_id: 'crs_aice_03',
        title: 'Module 1: Advanced Prompt Engineering & Cognitive Architectures',
        position: 1,
        lessons: [
          {
            id: 'les_aice_01',
            section_id: 'sec_aice_01',
            title: '1.1 System Prompts, Few-Shot Demonstrations & Chain-of-Thought',
            type: 'video',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
            content: 'Master structured prompting techniques to generate production deliverables, marketing campaigns, and research syntheses.',
            duration_seconds: 460,
            position: 1,
            is_free_preview: true,
            is_completed: false,
          },
        ],
      },
    ],
  },
  {
    id: 'crs_ai_ml_02',
    instructor_id: 'usr_instructor_001',
    title: 'Applied Deep Learning & Modern Transformer Architectures',
    slug: 'deep-learning-transformers',
    description: 'Build, fine-tune, and deploy attention mechanisms, LLMs, and computer vision models with PyTorch and production inference pipelines.',
    category: 'AI & Data',
    track: 'AI & Data',
    level: 'Advanced',
    outcome_hook: 'Build, fine-tune, and deploy attention mechanisms, LLMs, and scalable inference backends.',
    duration_weeks: 16,
    weekly_hours: '20-25 hrs/week',
    skills: ['PyTorch', 'Transformers', 'Hugging Face', 'CUDA', 'Vector Databases', 'LangChain'],
    sponsorship_note: 'Sponsored / $5/mo',
    is_now_open: true,
    is_popular: false,
    cohort_date: 'May 2026',
    price: 69.99,
    thumbnail_url: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    created_at: '2026-02-10T14:00:00Z',
    enrollments_count: 890,
    average_rating: 4.85,
    reviews_count: 178,
    instructor: DEFAULT_INSTRUCTOR_PROFILE,
    sections: [
      {
        id: 'sec_ml_01',
        course_id: 'crs_ai_ml_02',
        title: 'Module 1: Self-Attention & Transformer Core',
        position: 1,
        lessons: [
          {
            id: 'les_ml_01',
            section_id: 'sec_ml_01',
            title: '1.1 Mathematical Foundations of Scaled Dot-Product Attention',
            type: 'video',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
            content: 'Step-by-step vector breakdown of Query, Key, and Value projections.',
            duration_seconds: 540,
            position: 1,
            is_free_preview: true,
            is_completed: false,
          },
          {
            id: 'les_ml_02',
            section_id: 'sec_ml_01',
            title: '1.2 Self-Attention Quiz Checkpoint',
            type: 'quiz',
            duration_seconds: 300,
            position: 2,
            is_free_preview: false,
            is_completed: false,
            quiz_questions: [
              {
                id: 'q_ml_01',
                lesson_id: 'les_ml_02',
                question: 'Why is the dot-product scaled by sqrt(d_k) in scaled dot-product attention?',
                options: [
                  'To prevent gradients from vanishing when dot products grow excessively large in higher dimensions',
                  'To invert the attention matrix for backpropagation',
                  'To force the attention matrix to become symmetric',
                  'To reduce GPU memory allocation by 50%',
                ],
                correct_option_index: 0,
                explanation: 'Without scaling, large dimensional vectors produce large dot products, pushing the softmax function into regions with extremely small gradients.',
                position: 1,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'crs_cloud_devops_04',
    instructor_id: 'usr_instructor_001',
    title: 'Cloud DevOps & Site Reliability Engineering (AWS & Kubernetes)',
    slug: 'cloud-devops-site-reliability',
    description: 'Design, provision, and maintain high-availability cloud infrastructure. Master containerization with Docker, orchestration with Kubernetes, Infrastructure as Code with Terraform, and zero-downtime CI/CD pipelines.',
    category: 'Software Engineering',
    track: 'Software Engineering',
    level: 'Intermediate',
    outcome_hook: 'Design resilient cloud systems and CI/CD automation pipelines for high-growth tech firms.',
    duration_weeks: 20,
    weekly_hours: '20-25 hrs/week',
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'GitHub Actions', 'Prometheus & Grafana'],
    sponsorship_note: 'Sponsored / $5/mo',
    is_now_open: true,
    is_popular: false,
    cohort_date: 'May 2026',
    price: 54.99,
    thumbnail_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    created_at: '2026-02-18T11:00:00Z',
    enrollments_count: 1120,
    average_rating: 4.88,
    reviews_count: 240,
    instructor: DEFAULT_INSTRUCTOR_PROFILE,
    sections: [
      {
        id: 'sec_devops_01',
        course_id: 'crs_cloud_devops_04',
        title: 'Module 1: Container Orchestration & Zero-Downtime Deployments',
        position: 1,
        lessons: [
          {
            id: 'les_devops_01',
            section_id: 'sec_devops_01',
            title: '1.1 Multi-Stage Docker Builds & Minimal Production Images',
            type: 'video',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
            content: 'How to shrink Docker image sizes by 85% and secure container runtimes against root vulnerabilities.',
            duration_seconds: 490,
            position: 1,
            is_free_preview: true,
            is_completed: false,
          },
        ],
      },
    ],
  },
  {
    id: 'crs_ui_ux_03',
    instructor_id: 'usr_instructor_001',
    title: 'UI/UX Design Systems: From Design Tokens to Production Components',
    slug: 'ui-ux-design-systems',
    description: 'Learn the principles of modern human-centered interface design, contrast ratios, micro-interactions, and creating design systems that scale.',
    category: 'Creative & Design',
    track: 'Creative & Design',
    level: 'Beginner',
    outcome_hook: 'Build a career around your creativity and command real income doing it.',
    duration_weeks: 12,
    weekly_hours: '15-20 hrs/week',
    skills: ['Figma', 'Design Systems', 'Design Tokens', 'User Research', 'Interactive Prototyping'],
    sponsorship_note: 'Sponsored / $5/mo',
    is_now_open: true,
    is_popular: true,
    cohort_date: 'April 2026',
    price: 39.99,
    thumbnail_url: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    created_at: '2026-02-15T09:00:00Z',
    enrollments_count: 2150,
    average_rating: 4.95,
    reviews_count: 420,
    instructor: DEFAULT_INSTRUCTOR_PROFILE,
    sections: [
      {
        id: 'sec_ui_01',
        course_id: 'crs_ui_ux_03',
        title: 'Module 1: Color Theory, Visual Hierarchy & Accessibility',
        position: 1,
        lessons: [
          {
            id: 'les_ui_01',
            section_id: 'sec_ui_01',
            title: '1.1 Accessible Typography & Modern Color Tokens',
            type: 'video',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
            content: 'How to build WCAG AAA compliant color ramps and typographic rhythm.',
            duration_seconds: 420,
            position: 1,
            is_free_preview: true,
            is_completed: false,
          },
        ],
      },
    ],
  },
  {
    id: 'crs_content_creation_05',
    instructor_id: 'usr_instructor_001',
    title: 'Content Creation & Digital Media Strategy',
    slug: 'content-creation-digital-media',
    description: 'Turn your ideas into digital content that commands an audience and builds monetization streams. Learn multi-platform storytelling, video scripting, algorithm mechanics, and brand partnership negotiation.',
    category: 'Creative & Design',
    track: 'Creative & Design',
    level: 'Beginner',
    outcome_hook: 'Turn your ideas into content that earns and build a freelance or media career around it.',
    duration_weeks: 8,
    weekly_hours: '10-15 hrs/week',
    skills: ['Video Production', 'Copywriting', 'Short-form Video', 'YouTube Growth', 'Brand Sponsorships'],
    sponsorship_note: 'Sponsored / $5/mo',
    is_now_open: true,
    is_popular: false,
    cohort_date: 'Rolling Admissions',
    price: 34.99,
    thumbnail_url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    created_at: '2026-02-20T10:00:00Z',
    enrollments_count: 1870,
    average_rating: 4.89,
    reviews_count: 310,
    instructor: DEFAULT_INSTRUCTOR_PROFILE,
    sections: [
      {
        id: 'sec_content_01',
        course_id: 'crs_content_creation_05',
        title: 'Module 1: Hook Architecture & Narrative Retention',
        position: 1,
        lessons: [
          {
            id: 'les_content_01',
            section_id: 'sec_content_01',
            title: '1.1 The First 3 Seconds: Algorithmic Retention Dynamics',
            type: 'video',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            content: 'Craft visual hooks that capture viewer attention and drive high completion rates.',
            duration_seconds: 390,
            position: 1,
            is_free_preview: true,
            is_completed: false,
          },
        ],
      },
    ],
  },
  {
    id: 'crs_founder_academy_06',
    instructor_id: 'usr_instructor_001',
    title: 'Founder Academy: Venture Building & Market Launch',
    slug: 'founder-academy-venture-building',
    description: 'Launch a venture, build something that lasts, and create opportunities that extend beyond yourself. Learn lean validation, MVP rapid prototyping, customer discovery, unit economics, and pitching to top-tier African and global angel investors.',
    category: 'Entrepreneurship',
    track: 'Entrepreneurship',
    level: 'All Levels',
    outcome_hook: 'Launch a venture, validate your MVP, and secure early customers and capital.',
    duration_weeks: 16,
    weekly_hours: '15-20 hrs/week',
    skills: ['Lean Startup', 'Customer Discovery', 'Unit Economics', 'Pitch Decks', 'Seed Fundraising'],
    sponsorship_note: 'Mastercard Foundation Sponsored',
    is_now_open: true,
    is_popular: true,
    cohort_date: 'April 2026',
    price: 59.99,
    thumbnail_url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    created_at: '2026-02-22T08:00:00Z',
    enrollments_count: 1650,
    average_rating: 4.94,
    reviews_count: 280,
    instructor: DEFAULT_INSTRUCTOR_PROFILE,
    sections: [
      {
        id: 'sec_founder_01',
        course_id: 'crs_founder_academy_06',
        title: 'Module 1: Problem Space Discovery & Market Sizing',
        position: 1,
        lessons: [
          {
            id: 'les_founder_01',
            section_id: 'sec_founder_01',
            title: '1.1 The Mom Test & Unbiased Customer Interviews',
            type: 'video',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
            content: 'How to talk to prospective customers and uncover genuine willingness to pay without leading questions.',
            duration_seconds: 450,
            position: 1,
            is_free_preview: true,
            is_completed: false,
          },
        ],
      },
    ],
  },
  {
    id: 'crs_freelancer_07',
    instructor_id: 'usr_instructor_001',
    title: 'Freelancer Academy: High-Value Remote Consulting',
    slug: 'freelancer-academy-remote-consulting',
    description: 'Build a freelance career that generates consistent income on your own terms. Learn how to win high-ticket international contracts on Upwork, position yourself as an authority, and build recurring client retainers.',
    category: 'Entrepreneurship',
    track: 'Entrepreneurship',
    level: 'Beginner',
    outcome_hook: 'Build a freelance career that generates consistent global income entirely on your own terms.',
    duration_weeks: 8,
    weekly_hours: '10-15 hrs/week',
    skills: ['Client Acquisition', 'Upwork & Fiverr Optimization', 'High-Ticket Proposals', 'Contract Pricing'],
    sponsorship_note: 'Sponsored / $5/mo',
    is_now_open: true,
    is_popular: false,
    cohort_date: 'April 2026',
    price: 29.99,
    thumbnail_url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80',
    is_published: true,
    created_at: '2026-02-25T13:00:00Z',
    enrollments_count: 2420,
    average_rating: 4.91,
    reviews_count: 360,
    instructor: DEFAULT_INSTRUCTOR_PROFILE,
    sections: [
      {
        id: 'sec_free_01',
        course_id: 'crs_freelancer_07',
        title: 'Module 1: Positioning, Niche Selection & Portfolio Presentation',
        position: 1,
        lessons: [
          {
            id: 'les_free_01',
            section_id: 'sec_free_01',
            title: '1.1 Structuring Proposals that Win International Clients',
            type: 'video',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
            content: 'Writing high-conversion proposals that stand out from thousands of bids.',
            duration_seconds: 370,
            position: 1,
            is_free_preview: true,
            is_completed: false,
          },
        ],
      },
    ],
  },
];

export const SAMPLE_CBT_EXAMS: CBTExam[] = [
  {
    id: 'cbt_fullstack_cert_01',
    title: 'Full-Stack Web Engineering Certification CBT Mock',
    slug: 'fullstack-web-engineering-cbt',
    description: 'Comprehensive timed examination evaluating Next.js 15 App Router architecture, PostgreSQL RLS security, caching semantics, and client-server state boundaries.',
    category: 'Web Development',
    duration_minutes: 15,
    passing_score_percent: 70,
    total_questions: 6,
    difficulty: 'Intermediate',
    created_at: '2026-03-01T08:00:00Z',
    questions: [
      {
        id: 'cbt_q_01',
        exam_id: 'cbt_fullstack_cert_01',
        question: 'In a Next.js App Router application, how are React Server Components (RSC) rendered and delivered to the client browser?',
        options: [
          'They are compiled into WebAssembly binaries downloaded on initial page load',
          'They execute on the server and stream a compact JSON-like serialized UI tree without shipping component JavaScript to the client',
          'They execute inside a client-side Service Worker thread',
          'They convert all interactive hooks (useState/useEffect) into HTML data attributes',
        ],
        correct_option_index: 1,
        explanation: 'Server Components execute only on the server, serializing output into an RSC payload stream without adding to the client JavaScript bundle size.',
        topic: 'Next.js Architecture',
        position: 1,
      },
      {
        id: 'cbt_q_02',
        exam_id: 'cbt_fullstack_cert_01',
        question: 'When implementing multi-tenant isolation in Supabase PostgreSQL, which mechanism provides the strongest defense against accidental data leakage?',
        options: [
          'Using application-level WHERE clauses in every frontend query',
          'Enabling Row-Level Security (RLS) policies evaluated inside the Postgres database engine using auth.uid()',
          'Encrypting the entire database partition with AES-256',
          'Relying solely on HTTP CORS origin whitelisting',
        ],
        correct_option_index: 1,
        explanation: 'PostgreSQL Row-Level Security evaluates access rules at the engine level, guaranteeing that no API route or application bug can bypass row filtering.',
        topic: 'Database & Security',
        position: 2,
      },
      {
        id: 'cbt_q_03',
        exam_id: 'cbt_fullstack_cert_01',
        question: 'What is the primary benefit of utilizing Optimistic UI updates when a candidate submits an answer or progress checkpoint?',
        options: [
          'It eliminates database write operations entirely',
          'It updates local state instantaneously (<16ms) to provide zero perceived latency, rolling back only if the network request fails',
          'It caches the entire database in localStorage',
          'It automatically encrypts payload headers using RSA-2048',
        ],
        correct_option_index: 1,
        explanation: 'Optimistic UI assumes network success immediately to guarantee buttery-smooth responsiveness, rolling back if an error occurs.',
        topic: 'Client State',
        position: 3,
      },
      {
        id: 'cbt_q_04',
        exam_id: 'cbt_fullstack_cert_01',
        question: 'Which HTTP caching header directive ensures a browser revalidates cached content with the origin server before serving it from disk?',
        options: [
          'Cache-Control: no-store',
          'Cache-Control: no-cache',
          'Cache-Control: max-age=31536000, immutable',
          'Cache-Control: public, s-maxage=3600',
        ],
        correct_option_index: 1,
        explanation: 'no-cache allows storage in browser cache, but forces the browser to validate ETag/Last-Modified with the server before rendering.',
        topic: 'HTTP & Caching',
        position: 4,
      },
      {
        id: 'cbt_q_05',
        exam_id: 'cbt_fullstack_cert_01',
        question: 'In PostgreSQL, what indexing structure is best suited for accelerating equality queries against foreign keys like user_id in an enrollments table?',
        options: [
          'B-Tree Index',
          'GIN (Generalized Inverted Index)',
          'BRIN (Block Range Index)',
          'GiST (Generalized Search Tree)',
        ],
        correct_option_index: 0,
        explanation: 'B-Tree is the default and optimal index type for equality (=) and range (<, >, <=, >=) lookups on scalar values like UUID foreign keys.',
        topic: 'Database Systems',
        position: 5,
      },
      {
        id: 'cbt_q_06',
        exam_id: 'cbt_fullstack_cert_01',
        question: 'Which of the following describes an idempotent HTTP operation according to the RFC 9110 specification?',
        options: [
          'An operation that cannot be accessed over HTTPS',
          'An operation where making multiple identical requests has the same intended effect on the server as making a single request',
          'An operation that always returns an HTTP 200 status code',
          'An operation that never modifies server memory',
        ],
        correct_option_index: 1,
        explanation: 'Idempotency means that executing f(x) once produces the exact same server state as executing f(f(x)) multiple times (e.g. GET, PUT, DELETE).',
        topic: 'API Design',
        position: 6,
      },
    ],
  },
  {
    id: 'cbt_dsa_exam_02',
    title: 'Algorithms & Data Structures Technical Assessment CBT',
    slug: 'algorithms-data-structures-cbt',
    description: 'Timed algorithmic assessment covering asymptotic complexity analysis, graph traversals, dynamic programming, and balanced binary search trees.',
    category: 'Computer Science',
    duration_minutes: 20,
    passing_score_percent: 75,
    total_questions: 5,
    difficulty: 'Advanced',
    created_at: '2026-03-02T10:00:00Z',
    questions: [
      {
        id: 'dsa_q_01',
        exam_id: 'cbt_dsa_exam_02',
        question: 'What is the worst-case time complexity of searching for an element in an unaugmented AVL Tree with n nodes?',
        options: [
          'O(n)',
          'O(log n)',
          'O(n log n)',
          'O(1)',
        ],
        correct_option_index: 1,
        explanation: 'An AVL tree strictly enforces that heights of two child subtrees differ by at most 1, guaranteeing O(log n) height and lookup time even in the worst case.',
        topic: 'Trees & Graphs',
        position: 1,
      },
      {
        id: 'dsa_q_02',
        exam_id: 'cbt_dsa_exam_02',
        question: 'Which graph traversal algorithm finds the shortest path in an unweighted directed graph with V vertices and E edges in O(V + E) time?',
        options: [
          'Depth-First Search (DFS)',
          'Breadth-First Search (BFS)',
          'Dijkstra\'s Algorithm',
          'Bellman-Ford Algorithm',
        ],
        correct_option_index: 1,
        explanation: 'BFS explores vertices in order of their hop distance from the source, naturally yielding the shortest path in an unweighted graph in O(V + E) time.',
        topic: 'Graph Algorithms',
        position: 2,
      },
      {
        id: 'dsa_q_03',
        exam_id: 'cbt_dsa_exam_02',
        question: 'What dynamic programming technique avoids recursive call-stack overflow by iteratively filling a table from smallest subproblems upward?',
        options: [
          'Top-down memoization',
          'Bottom-up tabulation',
          'Divide and conquer',
          'Backtracking with pruning',
        ],
        correct_option_index: 1,
        explanation: 'Bottom-up tabulation iteratively computes subproblems in topological order without recursion overhead, avoiding stack overflows.',
        topic: 'Dynamic Programming',
        position: 3,
      },
      {
        id: 'dsa_q_04',
        exam_id: 'cbt_dsa_exam_02',
        question: 'What is the amortized time complexity of inserting n items into an initially empty dynamic array (like std::vector or Python list) that doubles capacity when full?',
        options: [
          'O(1) amortized per insertion',
          'O(n) amortized per insertion',
          'O(log n) amortized per insertion',
          'O(n^2) total',
        ],
        correct_option_index: 0,
        explanation: 'Although doubling takes O(n), it occurs infrequently. The aggregate cost of n insertions is 2n, resulting in O(1) amortized cost per element.',
        topic: 'Asymptotic Analysis',
        position: 4,
      },
      {
        id: 'dsa_q_05',
        exam_id: 'cbt_dsa_exam_02',
        question: 'Which collision resolution strategy in Hash Tables stores colliding key-value entries in linked lists or balanced trees at the same bucket index?',
        options: [
          'Linear Probing',
          'Quadratic Probing',
          'Separate Chaining',
          'Double Hashing',
        ],
        correct_option_index: 2,
        explanation: 'Separate Chaining maintains an auxiliary data structure (linked list or tree) at each hash bucket to hold keys with identical hashes.',
        topic: 'Data Structures',
        position: 5,
      },
    ],
  },
  {
    id: 'cbt_db_sql_03',
    title: 'PostgreSQL Database Architecture & Query Tuning CBT',
    slug: 'postgresql-database-tuning-cbt',
    description: 'Standardized assessment on MVCC, write-ahead logging (WAL), EXPLAIN ANALYZE interpretation, and transaction isolation anomalies.',
    category: 'Database Systems',
    duration_minutes: 15,
    passing_score_percent: 75,
    total_questions: 5,
    difficulty: 'Intermediate',
    created_at: '2026-03-03T11:00:00Z',
    questions: [
      {
        id: 'db_q_01',
        exam_id: 'cbt_db_sql_03',
        question: 'How does PostgreSQL achieve Multi-Version Concurrency Control (MVCC) without blocking readers during simultaneous writes?',
        options: [
          'By acquiring global table read locks',
          'By retaining multiple row versions identified by xmin/xmax transaction IDs so readers see consistent snapshots',
          'By storing uncommitted changes in browser memory',
          'By serializing all incoming client connections into a single queue',
        ],
        correct_option_index: 1,
        explanation: 'Postgres writes new row tuples with transaction identifiers (xmin/xmax), allowing readers to access snapshot versions without acquiring read locks.',
        topic: 'Postgres MVCC',
        position: 1,
      },
      {
        id: 'db_q_02',
        exam_id: 'cbt_db_sql_03',
        question: 'In an EXPLAIN ANALYZE execution plan, what does a "Seq Scan" (Sequential Scan) indicate?',
        options: [
          'Postgres used an index to quickly locate specific rows',
          'Postgres scanned all database disk blocks in the table sequentially from start to finish',
          'Postgres sorted the output using parallel merge sort',
          'Postgres cached the query result in Redis',
        ],
        correct_option_index: 1,
        explanation: 'A Seq Scan reads every page in the table sequentially. For large tables, adding a suitable index replaces this with an Index Scan or Bitmap Index Scan.',
        topic: 'Query Optimization',
        position: 2,
      },
      {
        id: 'db_q_03',
        exam_id: 'cbt_db_sql_03',
        question: 'Which transaction isolation anomaly can occur under the READ COMMITTED isolation level, but is prevented under REPEATABLE READ?',
        options: [
          'Dirty Read',
          'Non-Repeatable Read (Fuzzy Read)',
          'Serialization Failure',
          'Deadlock Abort',
        ],
        correct_option_index: 1,
        explanation: 'Under READ COMMITTED, each query sees a new snapshot. If another transaction commits a change between queries, a re-read will see different values (Non-Repeatable Read).',
        topic: 'ACID & Transactions',
        position: 3,
      },
      {
        id: 'db_q_04',
        exam_id: 'cbt_db_sql_03',
        question: 'What is the primary role of the PostgreSQL VACUUM process?',
        options: [
          'To compress video files in object storage',
          'To reclaim storage occupied by dead row versions (bloat) generated by UPDATE and DELETE operations',
          'To renew user SSL certificates',
          'To restart the database daemon upon crashes',
        ],
        correct_option_index: 1,
        explanation: 'VACUUM removes dead row versions that are no longer visible to active transactions, freeing space for new rows and updating planner statistics.',
        topic: 'Database Administration',
        position: 4,
      },
      {
        id: 'db_q_05',
        exam_id: 'cbt_db_sql_03',
        question: 'Why does Write-Ahead Logging (WAL) significantly improve database write performance while preserving ACID durability?',
        options: [
          'It writes changes sequentially to an append-only log on disk before modifying random data pages',
          'It skips writing data to permanent disk drives completely',
          'It compresses all database rows into zip archives',
          'It delegates transactions to remote client machines',
        ],
        correct_option_index: 0,
        explanation: 'Writing sequentially to the append-only WAL log is orders of magnitude faster than random writes to data tables, yet guarantees recovery during crashes.',
        topic: 'Storage & Recovery',
        position: 5,
      },
    ],
  },
];

export const SAMPLE_LIVE_ROOMS: LiveRoom[] = [
  {
    id: 'room_arch_office_hours_01',
    title: 'Full-Stack Architecture & Supabase RLS Office Hours',
    description: 'Weekly interactive office hours with Dr. Elena Chen. Bring your questions on PostgreSQL security policies, Next.js 15 Server Actions, and real-time state synchronization.',
    instructor_id: 'usr_instructor_001',
    instructor_name: 'Dr. Elena Chen',
    instructor_avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    course_id: 'crs_nextjs_supabase_01',
    course_title: 'Full-Stack Modern Web Engineering with Next.js 15 & Supabase',
    is_active: true,
    scheduled_time: 'Live Right Now',
    participant_count: 8,
    tags: ['Office Hours', 'Architecture', 'Live Q&A', 'Whiteboard'],
    created_at: '2026-03-10T14:00:00Z',
  },
  {
    id: 'room_dsa_clinic_02',
    title: 'Algorithms & Technical Problem Solving Clinic',
    description: 'Interactive diagramming and whiteboard session covering tree balancing, graph traversals, and dynamic programming patterns.',
    instructor_id: 'usr_instructor_001',
    instructor_name: 'Dr. Elena Chen',
    instructor_avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    course_id: 'crs_ai_ml_02',
    course_title: 'Applied Deep Learning & Modern Transformer Architectures',
    is_active: true,
    scheduled_time: 'Live Right Now',
    participant_count: 14,
    tags: ['Algorithms', 'Whiteboard', 'Coding Clinic'],
    created_at: '2026-03-11T16:00:00Z',
  },
  {
    id: 'room_project_review_03',
    title: '1-on-1 Student Project Review & Career Mentorship Lounge',
    description: 'Drop-in mentorship session for code walkthroughs, design system audits, and capstone project feedback.',
    instructor_id: 'usr_instructor_001',
    instructor_name: 'Dr. Elena Chen',
    instructor_avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    is_active: false,
    scheduled_time: 'Today at 5:30 PM UTC',
    participant_count: 4,
    tags: ['Mentorship', 'Code Review', 'Career'],
    created_at: '2026-03-12T10:00:00Z',
  },
];

export const INITIAL_ROOM_PARTICIPANTS: Record<string, LiveParticipant[]> = {
  room_arch_office_hours_01: [
    {
      id: 'usr_instructor_001',
      name: 'Dr. Elena Chen (Host)',
      avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
      role: 'instructor',
      is_speaking: true,
      is_muted: false,
      is_camera_on: true,
    },
    {
      id: 'usr_student_010',
      name: 'Jordan Taylor',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      role: 'student',
      is_speaking: false,
      is_muted: true,
      is_camera_on: true,
      has_hand_raised: false,
    },
    {
      id: 'usr_student_002',
      name: 'Sophia Zhang',
      avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
      role: 'student',
      is_speaking: false,
      is_muted: true,
      is_camera_on: true,
    },
    {
      id: 'usr_student_003',
      name: 'Liam Patel',
      avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80',
      role: 'student',
      is_speaking: false,
      is_muted: true,
      is_camera_on: false,
    },
  ],
};

export const INITIAL_ROOM_MESSAGES: Record<string, LiveChatMessage[]> = {
  room_arch_office_hours_01: [
    {
      id: 'msg_01',
      room_id: 'room_arch_office_hours_01',
      sender_id: 'usr_instructor_001',
      sender_name: 'Dr. Elena Chen',
      sender_avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
      sender_role: 'instructor',
      message: 'Welcome everyone! Today we are discussing PostgreSQL Row-Level Security optimizations and live debugging. Feel free to use the Whiteboard or raise your hand to speak.',
      timestamp: '14:02',
      is_announcement: true,
    },
    {
      id: 'msg_02',
      room_id: 'room_arch_office_hours_01',
      sender_id: 'usr_student_002',
      sender_name: 'Sophia Zhang',
      sender_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
      sender_role: 'student',
      message: 'Hi Dr. Chen! Can you demonstrate how auth.uid() interacts with security definer functions on the whiteboard?',
      timestamp: '14:04',
    },
    {
      id: 'msg_03',
      room_id: 'room_arch_office_hours_01',
      sender_id: 'usr_instructor_001',
      sender_name: 'Dr. Elena Chen',
      sender_avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
      sender_role: 'instructor',
      message: 'Great question Sophia! I am opening the Collaborative Whiteboard tab now so we can diagram the call chain.',
      timestamp: '14:05',
    },
  ],
};

// ==========================================
// Subscription Plans (Catalog & Pricing)
// ==========================================

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'term',
    name: 'Term Scholar Pass',
    tagline: 'Ideal for semester coursework and targeted sprint completion',
    price: 149,
    period: '/ semester',
    popular: false,
    features: [
      'Full access to all engineering curricula & video streams',
      'Standard CBT Examination test attempts (up to 3 / month)',
      'Community discussion forums & peer Q&A',
      'Downloadable code repositories & starter templates',
      'Intranet access granted upon admin tuition verification',
    ],
    intranet_perks: [
      'Standard Campus Intranet Access',
      'CBT Examination Center (Level 1)',
      'Community Bulletin Board',
    ],
  },
  {
    id: 'annual',
    name: 'Annual Campus Fellowship',
    tagline: 'Complete year-round access to the full academic suite and live faculty rooms',
    price: 299,
    period: '/ academic year',
    popular: true,
    features: [
      'Unlimited access to all existing and newly released courses',
      'Priority access to Live Virtual Meeting Rooms & Office Hours',
      'Unlimited CBT Certification exams with official digital credential slips',
      'Interactive Screen Sharing & Breakout Room participation',
      'Priority Admin Clearance queue (instant fast-track review)',
      'Internal Academic Code Sandbox & Research Repositories',
    ],
    intranet_perks: [
      'Full Campus Intranet VIP Clearance',
      'Live Virtual Rooms & Faculty Office Hours',
      'Unlimited CBT Testing Center',
      'Internal Library & Research Archive',
    ],
  },
  {
    id: 'lifetime',
    name: 'Distinguished Fellow Pass',
    tagline: 'Permanent lifetime alumni status with direct faculty mentoring and private workshops',
    price: 499,
    period: 'one-time investment',
    popular: false,
    features: [
      'Lifetime non-expiring clearance to all current and future portals',
      'Direct 1-on-1 scheduled office hours with Dr. Chen and senior faculty',
      'Lifetime access to CBT Examination re-takes & archival transcripts',
      'Host & Presenter privileges in collaborative student rooms',
      'Direct contact channel with the Academic Dean & Admin panel',
    ],
    intranet_perks: [
      'Permanent Intranet Clearance with Alumni Badge',
      'Presenter Privileges in Virtual Rooms',
      'Direct Faculty Mentorship Channel',
    ],
  },
];

// ==========================================
// Intranet Access Requests (Admin Clearance Queue)
// ==========================================

export const SAMPLE_INTRANET_REQUESTS: IntranetAccessRequest[] = [
  {
    id: 'req_001',
    user_id: 'usr_applicant_001',
    user_name: 'Marcus Vance',
    user_email: 'marcus.vance@campus.edu',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    plan_id: 'annual',
    plan_name: 'Annual Campus Fellowship',
    amount_paid: 299,
    payment_method: 'credit_card',
    payment_reference: 'TXN-REACTJAV-8921B',
    payment_date: '2026-09-14T18:30:00Z',
    status: 'pending_approval',
    admin_granted: false,
  },
  {
    id: 'req_002',
    user_id: 'usr_student_002',
    user_name: 'Marcus Brody',
    user_email: 'marcus.brody@mit.edu',
    user_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    plan_id: 'term',
    plan_name: 'Term Scholar Pass',
    amount_paid: 149,
    payment_method: 'bank_transfer',
    payment_reference: 'TXN-WIRE-44199A',
    payment_date: '2026-09-14T16:15:00Z',
    status: 'pending_approval',
    admin_granted: false,
  },
  {
    id: 'req_003',
    user_id: 'usr_student_003',
    user_name: 'Aisha Patel',
    user_email: 'aisha.patel@oxford.ac.uk',
    user_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    plan_id: 'lifetime',
    plan_name: 'Distinguished Fellow Pass',
    amount_paid: 499,
    payment_method: 'credit_card',
    payment_reference: 'TXN-REACTJAV-1002C',
    payment_date: '2026-09-13T09:00:00Z',
    status: 'active',
    admin_granted: true,
    reviewed_at: '2026-09-13T10:15:00Z',
    reviewed_by: 'System Administrator (usr_admin_001)',
  },
  {
    id: 'req_004',
    user_id: 'usr_student_004',
    user_name: 'Devon Vance',
    user_email: 'devon.vance@stanford.edu',
    user_avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
    plan_id: 'term',
    plan_name: 'Term Scholar Pass',
    amount_paid: 149,
    payment_method: 'campus_voucher',
    payment_reference: 'VCH-EXPIRED-992',
    payment_date: '2026-09-12T14:20:00Z',
    status: 'rejected',
    admin_granted: false,
    reviewed_at: '2026-09-12T15:00:00Z',
    reviewed_by: 'System Administrator (usr_admin_001)',
    rejection_reason: 'Voucher code expired on 2026-09-01. Please submit fresh payment receipt.',
  },
];

// ==========================================
// Campus Bulletins & Intranet Announcements
// ==========================================

export const CAMPUS_BULLETINS: IntranetBulletin[] = [
  {
    id: 'blt_01',
    title: 'Q3 Distributed Systems CBT Certification Exam Window Open',
    category: 'Exam',
    priority: 'high',
    author: 'Examination Board',
    author_role: 'Academic Registrar',
    content: 'The official 60-minute CBT testing session for Advanced PostgreSQL & Distributed Locks is now active in the CBT Center. Cleared students are eligible for up to 3 attempts with automated credential generation.',
    created_at: '2026-09-15T08:00:00Z',
  },
  {
    id: 'blt_02',
    title: 'Dr. Elena Chen Live Architecture Office Hours (Screen-Sharing Workshop)',
    category: 'Lecture',
    priority: 'normal',
    author: 'Dr. Elena Chen',
    author_role: 'Faculty Lead',
    content: 'Room #01 will host a collaborative session on SubQuery optimizations and real-time screen annotations today at 14:00 GMT. Students can join via the Virtual Rooms hub.',
    created_at: '2026-09-15T09:30:00Z',
  },
  {
    id: 'blt_03',
    title: 'Campus Intranet Security Patch & Database Read-Replica Sync',
    category: 'Maintenance',
    priority: 'low',
    author: 'Campus IT Operations',
    author_role: 'System Administrator',
    content: 'Routine security indexing scheduled tonight at 02:00 UTC. Live rooms and CBT tests will maintain full availability with zero expected downtime.',
    created_at: '2026-09-14T22:00:00Z',
  },
];

// ==========================================
// Sample Student CBT/CDT Exam Attempts
// ==========================================

export const SAMPLE_CBT_ATTEMPTS: CBTAttempt[] = [
  {
    id: 'att_cbt_01',
    user_id: 'usr_cbt_sample_01',
    exam_id: 'cbt_exam_01',
    exam_title: 'Full-Stack Modern Web Engineering with Next.js 15 & Supabase Certification',
    score: 92,
    passed: true,
    total_questions: 5,
    answered_count: 5,
    correct_count: 5,
    time_spent_seconds: 780,
    answers: { 'q_01': 1, 'q_02': 1, 'q_03': 1, 'q_04': 0, 'q_05': 1 },
    flagged_questions: [],
    created_at: '2026-09-14T14:30:00Z',
  },
  {
    id: 'att_cbt_02',
    user_id: 'usr_cbt_sample_01',
    exam_id: 'cbt_dsa_exam_02',
    exam_title: 'Data Structures, Graph Theory & Algorithmic Complexity Benchmark',
    score: 84,
    passed: true,
    total_questions: 5,
    answered_count: 5,
    correct_count: 4,
    time_spent_seconds: 940,
    answers: { 'dsa_q_01': 1, 'dsa_q_02': 1, 'dsa_q_03': 1, 'dsa_q_04': 0, 'dsa_q_05': 2 },
    flagged_questions: ['dsa_q_04'],
    created_at: '2026-09-15T11:15:00Z',
  },
  {
    id: 'att_cbt_03',
    user_id: 'usr_cbt_sample_01',
    exam_id: 'cbt_exam_03',
    exam_title: 'PostgreSQL Row-Level Security, Database Indexing & Concurrency Control',
    score: 88,
    passed: true,
    total_questions: 5,
    answered_count: 5,
    correct_count: 4,
    time_spent_seconds: 820,
    answers: { 'pg_01': 1, 'pg_02': 0, 'pg_03': 2, 'pg_04': 1, 'pg_05': 0 },
    flagged_questions: [],
    created_at: '2026-09-16T10:00:00Z',
  },
];

// ==========================================
// Direct Tutoring Attendance Records (Dual Sign-off)
// ==========================================

export const INITIAL_TUTORING_ATTENDANCE: TutoringAttendanceSession[] = [];

